### ISSUE TITLE
Nginx custom log

### ISSUE THREAD

**Issue by yuynagforhacker** [cfsego/ngx_log_if#13]
Hello,
I have a problem and need help.
1.How to filter a custom log type?
like this:
`access_log logs/access.log mylog;`

2.By default, the child configuration block overrides the parent configuration block and does not inherit the configuration of the parent configuration block. So what happens if the child configuration block normally logs all logs and the parent configuration block configures the filter?
like this:
```
server{access_log_bypass_if ($status = 200);access_log logs/access_if.log;
location /test {access_log logs/access.log;}}

```
thanks all.

**Comment by cfsego** [comment]
1. in your case, are you going to filter "mylog"? you can not do like that. you should add different "access_log" configurations and use them separately in different location or server blocks.

2. because "access_log_bypass_if" and "access_log" are two directives, they are two configurations, so "access_log" in location block overrides it in server block, however, there is no "access_log_bypass_if" in  location block, its server configuration is inherited.

**Comment by yuynagforhacker** [comment]
Ok, I understand, thank you.
